# JXSensorMsg
Header header

float32 atm_humid   # Atmospheric humidity,     %RH
float32 atm_temp    # Atmospheric temperature,  ℃
int32  co_ppm      # CO gas concentration,     ppm
int32  co2_ppm     # CO2 gas concentration,    ppm
int32  ch4_ppm     # CH4 gas concentration,    ppm
float32 pm2_5_vol   # PM2.5 concentration,      ug/m^3
float32 pm10_vol    # PM10 concentration,       ug/m^3
float32 gas_concen  # Gas concentration
#float32 atm_press   # Atmospheric pressure,     Mbar

